<div>
	<picture>
		<source srcset="/img/flower_transparent_150.webp" type="image/webp">
		<img src="/img/flower_transparent_150.png" height="150" alt="Homepage" data-source="https://derpibooru.org/images/3120357" usemap="#jimmagemap">
	</picture>

	<!-- Image Map Generated by http://www.image-map.net/ -->
	<map name="jimmagemap" data-scaled=true>
		<area alt="Homepage" title="Homepage" href="/" data-j coords="3,60,0,43,7,28,16,20,28,13,10,11,22,1,46,1,57,3,66,8,74,16,74,1,82,8,85,16,85,23,104,9,106,28,101,37,90,43,95,55,95,66,86,81,87,91,91,97,78,96,85,104,90,114,93,127,93,139,71,140,67,146,61,149,53,149,47,144,41,144,37,137,47,122,47,110,50,107,48,98,49,95,56,101,56,91,54,87,43,87,38,93,43,95,43,98,40,103,42,105,40,111,36,110,34,114,29,114,28,110,22,110,22,104,24,102,24,94,30,93,32,97,41,87,34,87,26,84,17,72,19,63,25,60,26,46" shape="poly">
	</map>
</div>
