
<div id=homepage>
	<div id=overlay1>
		<!--<img class="cookie_webp" src="/img/cookie_transparent.webp" alt="My OC floating on a cookie by Tiny Jasmini" data-source="https://derpibooru.org/images/3055814">-->
		<img src="/img/jimm.webp" data-source="https://derpibooru.org/images/3022375" alt="My OC sitting by Dyonys">
	</div>
	<div id=overlay2 aria-hidden="true">
	</div>

	<div class=sidecol>
		<a data-j href="/chili">
			<img class=pixelated src="/img/angelcooking.gif" width=128 alt="Link to chili" title="Chili recipe">
		</a>

		<a href="http://automaticbeyondbelief.com">
			<img class=pixelated width=128 src="/img/sunbeam.jpg" title="I bought one of these and fixed it; highly recommended" alt="Link to Automatic Beyond Belief">
		</a>

		<img class=pixelated src="/img/jimmexcited.gif" width=128 usemap="#bsdmap">
		<map name="bsdmap">
			<area id="bsdmap" shape="poly" 
			coords="69,6,73,6,77,6,81,6,85,6,85,10,89,10,93,10,95,12,95,16,97,18,97,22,99,24,101,26,101,30,103,32,103,36,103,40,101,42,92,43,89,45,89,49,89,51,87,53,85,55,83,57,81,59,81,63,81,67,81,71,81,75,81,79,86,78,90,78,92,80,94,82,95,85,95,89,95,93,95,97,95,101,93,103,93,105,89,109,87,111,84,113,78,115,75,112,74,113,73,117,73,121,73,123,64,125,56,125,48,121,40,121,32,121,30,113,26,105,28,100,26,97,22,93,24,88,26,82,20,75,20,67,22,62,26,60,30,58,32,52,36,52,39,53,40,47,40,40,44,36,46,30,48,24,50,18,52,12,55,10,57,12" 
			alt="Link to my NetBSD site" title="Link to my NetBSD site" href="http://armchair.dashtel.ca/~jimm/index.html">
		</map>
	</div>

	<main>
		<div class=txt>
			<span>Hey, I'm Jimm!</span>
		</div>
		<br>
		<div class=txt>
			<span>I work on <a href="https://overmare.studio/">Ashes of Equestria</a>, <a href="https://legendsofequestria.com">Legends of Equestria</a>, and various other horse projects.</span>
		</div>
	</main>

	<div class=sidecol>
		<img src="/img/twitter_128.gif" alt="Twitter" width=128 data-source="https://cliply.co/clip/twitter-logo/" usemap="#twittermap">
		<map name="twittermap">
			<area 
				id="twittermap" 
				shape="poly" 
				coords="80,16,76,17,83,17,87,17,90,18,92,20,95,21,99,22,103,21,107,19,108,21,108,25,111,26,111,30,111,34,108,36,106,38,104,40,102,42,102,45,102,49,101,52,100,56,100,59,101,63,105,63,108,64,112,64,109,67,107,69,105,71,102,73,100,74,94,75,92,77,94,81,92,82,87,84,84,86,82,88,82,89,79,91,75,93,75,94,70,96,64,98,64,99,57,100,48,101,43,102,35,101,28,99,21,96,17,90,19,86,23,86,27,85,31,85,35,82,30,78,27,71,29,68,24,64,20,57,21,51,22,46,20,39,21,31,24,28,25,31,27,33,29,35,34,35,36,35,38,37,40,39,42,41,44,43,47,44,52,44,54,44,56,46,59,47,63,39,63,31,66,25,70,21,74,18,65,27,63,36,63,44"
				alt="Twitter" 
				href="https://twitter.com/JimmJamme/">
		</map>

		<img src="/img/github-mark-white.svg" width=128 usemap="#githubmap">
		<map name="githubmap">
			<area shape="circle" coords="64,64,64" href="https://github.com/ldyeax/" alt="GitHub">
		</map>

		<img src="/img/e_mail.gif" alt="Email" width=128 class=pixelated usemap="#emailmap" data-source="https://web.archive.org/web/20090820060950im_/http://geocities.com/TheTropics/Shores/4374/e_mail.gif">
		<!-- Image Map Generated by http://www.image-map.net/ -->
		<map name="emailmap">
			<area alt="Email" href="mailto:jimm@jimm.horse" coords="5,34 16,38 33,30 34,20 35,20 35,7 27,2 21,5 14,4 6,7 6,21 10,24 4,27" shape="polygon">
			<area alt="Email" href="mailto:jimm@jimm.horse" coords="112,39 96,30 95,25 97,22 93,21 93,6 102,1 108,4 117,3 123,7 123,21 118,24 125,25 125,33" shape="polygon">
			<area alt="Email" href="mailto:jimm@jimm.horse" coords="102,11,32,26" shape="rect">
		</map>
	</div>
</div>
